package project;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;

@SuppressWarnings("ALL")
public class Project {
    private static Random random = new Random();
    private static int north = 0;
    private static int south = 0;
    private static int east = 0;
    private static int west = 0;
    private static int northborder = random.nextInt(50, 75);
    private static int southborder = random.nextInt(50, 75);
    private static int eastborder = random.nextInt(50, 75);
    private static int westborder = random.nextInt(50, 75);
    private static int northeastborder = random.nextInt(25, 50);
    private static int southwestborder = random.nextInt(25, 50);
    public static boolean game;
    public static String endtext;
    private JLabel text;
    private JPanel window;
    private JTextField input;
    private JButton enter;

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        Project gui = new Project();
        gui.createUIComponents();

        frame.setSize(300, 300);
        frame.setVisible(true);

        frame.add(gui.window);
        /*game = true;
        Scanner input = new Scanner(System.in);
        System.out.println("You are in a forest with no way out,\nYou only hava a dagger\nand you must find your way out");
        while (game) {
            if (north > northeastborder && east > northeastborder) {
                endtext = "You got out of the forest";
                game = false;
            } else if (south > southwestborder && west > southwestborder) {
                endtext = "You got out of the forest";
                game = false;
            } else if (north > northborder) {
                endtext = "You got out of the forest";
                game = false;
            } else if (south > southborder) {
                endtext = "You got out of the forest";
                game = false;
            } else if (east > eastborder) {
                endtext = "You got out of the forest";
                game = false;
            } else if (west > westborder) {
                endtext = "You got out of the forest";
                game = false;
            } else {
                System.out.print("Enter your next move: ");
                String move;
                move = input.nextLine();
                new steps(move);

            }
        }
        System.out.print(endtext);*/
    }

    public static void setDirection(int north, int south, int east, int west) {
        Project.north = north;
        Project.south = south;
        Project.east = east;
        Project.west = west;
    }

    public static int getNorth() {
        return north;
    }

    public static int getSouth() {
        return south;
    }

    public static int getEast() {
        return east;
    }

    public static int getWest() {
        return west;
    }

    public Project() {
        $$$setupUI$$$();
        enter.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(enter, "HI", "hi", JOptionPane.PLAIN_MESSAGE);
            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        window = new JPanel();
        window.setLayout(new GridBagLayout());
        text = new JLabel();
        text.setText("Label");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        window.add(text, gbc);
        input = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        window.add(input, gbc);
        enter = new JButton();
        enter.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        window.add(enter, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return window;
    }

}
